theme: jekyll-theme-midnight
title: wrappi
description: A profiling library based on PAPI hardware counters targetted for Linux-based multicore compute nodes.
image: https://hobywan.github.io/wrappi/figures/logo.png
